version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    networks:
      - erudio-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: '*Rgh252817'
      MYSQL_DATABASE: grafica_kotlin
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - erudio-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/grafica_kotlin
    volumes:
      - .m2:/root/.m2
  front:
    image: rafaelassumpcao274/unilithfront:latest
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - erudio-network
#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    networks:
#      - erudio-network
#    ports:
#      - 88:80
#    environment:
#      PMA_HOST: db:3306
#      MYSQL_ROOT_PASSWORD: '*Rgh252817'

networks:
  erudio-network:
